version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin 
    networks:
      - wpsite
  # Apache
  apache:
    build:
      context: .
      dockerfile: ./apache.Dockerfile
    depends_on:
      - db
    ports:
      - '8080:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
    volumes:
      - ./webapp/:/var/www/html/webapp/
      - ./wordpress:/var/www/html/wordpress/
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
